title: hasgoodui.design
timezone: Europe/Zurich
collections:
  uploads:
    title: Uploads
    output: true
  authors:
    title: Authors
    output: false
markdown: kramdown
highlighter: rouge
lsi: false
description: Main website of the hasgoodui.design Organisation.
baseurl: ""
url: https://we-are.hasgoodui.design
color: "#0d1117"

github-repo: 'we-are'

footer-description: Main website of the hasgoodui.design Organisation.

plugins:
  - github-pages
  - jekyll-octicons
  - tzinfo-data
