name: Deploy to gh-pages

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/publish-site.yml'
      - 'docs/**'
      - 'requirements.txt'
      - 'mkdocs.yml'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python_version: 3.x
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build Docs
        run: mkdocs build
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          cname: we-are.hasgoodui.design
